-- TO_DO default값 setting

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(1, '가사일', SYSDATE, SYSDATE, 'PROGRESS');

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(2, '설겆이', SYSDATE, SYSDATE, 'PROGRESS');

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(3, '청소', SYSDATE, SYSDATE, 'PROGRESS');

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(4, '빨래', SYSDATE, SYSDATE, 'PROGRESS');

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(5, '숙제', SYSDATE, SYSDATE, 'DONE');

INSERT INTO TO_DO(ID, WHAT_TO_DO, REGISTER_DATE, LAST_UPDATE_DATE, STATUS)
VALUES(6, '여행계획', SYSDATE, SYSDATE, 'PROGRESS');

-- TO_DO default값 setting END


-- REFERENCE default값 setting

INSERT INTO REFERENCE(PARENT_ID, CHILD_ID, CHILD_STATUS)
VALUES(1, 2, 'PROGRESS');

INSERT INTO REFERENCE(PARENT_ID, CHILD_ID, CHILD_STATUS)
VALUES(1, 3, 'PROGRESS');

INSERT INTO REFERENCE(PARENT_ID, CHILD_ID, CHILD_STATUS)
VALUES(1, 4, 'PROGRESS');

-- REFERENCE default값 setting END